# Generated by Django 4.1 on 2022-08-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
