# Generated by Django 4.1 on 2022-08-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_post', '0002_remove_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='تخفیف'),
        ),
    ]
