# Generated by Django 4.1 on 2022-08-05 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_post', '0003_alter_books_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2022, 8, 5, 17, 12, 25, 602362, tzinfo=datetime.timezone.utc), upload_to='images/', verbose_name='عکس'),
            preserve_default=False,
        ),
    ]
