# Generated by Django 4.1 on 2022-08-05 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_post', '0004_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=datetime.datetime(2022, 8, 5, 17, 18, 24, 818145, tzinfo=datetime.timezone.utc), max_length=1000, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
